name: Build and deploy the site

#on:
#  push:
#    branches: [main]

env:
  HUGO_VERSION: '0.82.0'

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          clean: true
          submodules: false

      - name: Setup Hugo v${{ env.HUGO_VERSION }}
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public